"""Initial migration.

Revision ID: 259c4022c683
Revises: 
Create Date: 2021-11-06 10:48:21.753822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "259c4022c683"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # first we need to create custom schema named "content"
    op.execute("create schema content")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="content",
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("is_staff", sa.Boolean(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("created_on", sa.DateTime(),
                  server_default=sa.func.now(),
                  nullable=False),
        sa.Column("updated_on", sa.DateTime(),
                  server_default=sa.func.now(),
                  server_onupdate=sa.func.now(),
                  nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("login"),
        schema="content",
    )
    op.create_table(
        "roles_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["content.role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["content.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="content",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles_users", schema="content")
    op.drop_table("user", schema="content")
    op.drop_table("role", schema="content")

    op.execute("drop schema content")
    # ### end Alembic commands ###
