"""User login_email unique together added

Revision ID: 424b1ab32339
Revises: 2418b094fffd
Create Date: 2022-01-03 16:24:17.122335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "424b1ab32339"
down_revision = "2418b094fffd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "login_email_uc", "users", ["login", "email"], schema="content"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("login_email_uc", "users", schema="content", type_="unique")
    # ### end Alembic commands ###
