"""Role extended.

Revision ID: 48151ca253ee
Revises: 259c4022c683
Create Date: 2021-11-07 20:52:08.929358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import MetaData, Table

revision = "48151ca253ee"
down_revision = "259c4022c683"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column("description", sa.String(length=255), nullable=True),
        schema="content",
    )
    op.add_column(
        "roles", sa.Column("is_active", sa.Boolean(), default=True), schema="content"
    )

    # find existing table
    meta = MetaData(bind=op.get_bind())
    meta.reflect(only=("roles",), schema="content")
    roles_table = Table("roles", meta, schema="content")

    # create default roles that needed for base permissions assigning
    op.bulk_insert(
        roles_table,
        [
            {
                "name": "guest",
                "is_active": True,
                "description": "Designates that this user has basic permissions.",
            },
            {
                "name": "superuser",
                "is_active": True,
                "description": "Designates that this user has all permissions without explicitly assigning them.",
            },
            {
                "name": "staff",
                "is_active": True,
                "description": "Designates whether this user can access the admin service.",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "is_active", schema="content")
    op.drop_column("roles", "description", schema="content")
    # ### end Alembic commands ###
