"""users activities history

Revision ID: 93a756470bc9
Revises: 4fc1d4f05384
Create Date: 2021-11-18 19:14:59.476425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "93a756470bc9"
down_revision = "4fc1d4f05384"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("user_agent", sa.Text(), nullable=False),
        sa.Column("ip_addr", sa.String(length=100)),
        sa.Column("device", sa.Text()),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["content.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="content",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_history", schema="content")
    # ### end Alembic commands ###
