"""auth history platform

Revision ID: c40eccbbe099
Revises: 424b1ab32339
Create Date: 2022-01-17 23:46:05.419465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "c40eccbbe099"
down_revision = "424b1ab32339"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_history",
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        schema="content",
    )
    op.add_column(
        "auth_history",
        sa.Column(
            "updated_on",
            sa.DateTime(),
            server_default=sa.text("now()"),
            server_onupdate=sa.text("now()"),
            nullable=True,
        ),
        schema="content",
    )

    # # create enum object type
    platformenum = postgresql.ENUM("pc", "mobile", "tablet", name="platformenum")
    platformenum.create(op.get_bind())
    op.add_column(
        "auth_history",
        sa.Column(
            "platform",
            postgresql.ENUM("pc", "mobile", "tablet", name="platformenum"),
            server_default="pc",
            nullable=False,
        ),
        schema="content",
    )

    op.add_column(
        "social_accounts",
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        schema="content",
    )
    op.add_column(
        "social_accounts",
        sa.Column(
            "updated_on",
            sa.DateTime(),
            server_default=sa.text("now()"),
            server_onupdate=sa.text("now()"),
            nullable=True,
        ),
        schema="content",
    )
    op.create_unique_constraint("id_uc", "social_accounts", ["id"], schema="content")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("id_uc", "social_accounts", schema="content", type_="unique")
    op.drop_column("social_accounts", "updated_on", schema="content")
    op.drop_column("social_accounts", "created_on", schema="content")

    # drop enum object type
    op.drop_column("auth_history", "platform", schema="content")
    platformenum = postgresql.ENUM("pc", "mobile", "tablet", name="platformenum")
    platformenum.drop(op.get_bind())

    op.drop_column("auth_history", "updated_on", schema="content")
    op.drop_column("auth_history", "created_on", schema="content")
    # ### end Alembic commands ###
