"""auth_history

Revision ID: ca37f9f4d775
Revises: 4fc1d4f05384
Create Date: 2021-11-18 18:37:49.857748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca37f9f4d775'
down_revision = '4fc1d4f05384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('ip_addr', sa.String(length=100), nullable=False),
    sa.Column('device', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_unique_constraint(None, 'roles', ['id'], schema='content')
    op.create_unique_constraint(None, 'users', ['id'], schema='content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='content', type_='unique')
    op.drop_constraint(None, 'roles', schema='content', type_='unique')
    op.drop_table('auth_history', schema='content')
    # ### end Alembic commands ###
