"""2partition2

Revision ID: e459c3fcf52b
Revises: 93a756470bc9
Create Date: 2021-11-30 17:08:19.587628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e459c3fcf52b"
down_revision = "93a756470bc9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auth_history",
        "device",
        existing_type=sa.TEXT(),
        nullable=False,
        schema="content",
    )
    op.create_unique_constraint(None, "auth_history", ["id"], schema="content")
    op.create_unique_constraint(
        None, "auth_history", ["id", "device"], schema="content"
    )
    op.create_unique_constraint(None, "roles", ["id"], schema="content")
    op.create_unique_constraint(None, "users", ["id"], schema="content")
    op.create_unique_constraint(None, "users", ["id", "created_on"], schema="content")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", schema="content", type_="unique")
    op.drop_constraint(None, "users", schema="content", type_="unique")
    op.drop_constraint(None, "roles", schema="content", type_="unique")
    op.drop_constraint(None, "auth_history", schema="content", type_="unique")
    op.drop_constraint(None, "auth_history", schema="content", type_="unique")
    op.alter_column(
        "auth_history",
        "device",
        existing_type=sa.TEXT(),
        nullable=True,
        schema="content",
    )
    # ### end Alembic commands ###
